### ISSUE TITLE
Register external decoders/encoder

### ISSUE THREAD

**Issue by koenvo** [aiortc/aiortc#116]
First of all.. great library! 

Two questions:
1. I'm trying to get the raw h264 bitstream from a client without already decoding it. In my case I would like to push the undecoded data to AWS Kinesis Video for further processing. After reading the reddit discussing about following the WebRTC API I was kind of confused if this would be possible in a clean way because the data shouldn't be exposed at all.
2. In the WebRTC Native Code they use a CodecDatabase to get the decoder/encoders from. This would give me some more flexibility to register my own implementation of the H264Decoder. The current implementation with get_decoder doesn't leave any room to register a different version. Is this change wanted and/or are you already changing it? (I saw some commits touching the codecs code).

**Comment by jlaine** [comment]
Hi @koenvo !

A generic mechanism for registering encoders / decoders unfortunately sounds like a long shot. I'm progressively discovering that codecs are not just "plug & play", they usually extend quite far throughout the WebRTC stack: how you process the RTP payload, what feedback mechanisms are available, the jitter buffer, how you report picture loss over RTCP, etc.. I'm not too confident writing a public API for all this.

However your specific usecase sounds simpler, since you are in effect replacing an existing decoder. This is Python, and not compiled code, so you can monkey-patch `get_decoder` without needing to actually change `aiortc` and I'm pretty sure you can achieve what you want. I suggest you start by exploring this route, and report back with your findings.

**Comment by koenvo** [comment]
Good one. Will start with monkey patching!

**Comment by jlaine** [comment]
Cool! Once you have some proof-of-concept code I'd be very interested in seeing it.

**Comment by BloodyF** [comment]
Hi @jlaine 
BTW, how can I integrate my H264 hardware encoder? I am able to do this in c++ by inheriting some encoder classes of Google Webrtc Native, but I dont know how to do with aiortc.
 Someone told me to feed H264 stream into v4l2loopback device and use this dev as a normal /dev/video0. Do you think it's feasible?
Thank you

**Comment by BloodyF** [comment]
> Hi @jlaine
> BTW, how can I integrate my H264 hardware encoder? I am able to do this in c++ by inheriting some encoder classes of Google Webrtc Native, but I dont know how to do with aiortc.
> Someone told me to feed H264 stream into v4l2loopback device and use this dev as a normal /dev/video0. Do you think it's feasible?
> Thank you

Hi @jlaine 
How is it going? Now I am having a raw H264 bitstream in buffer, how can I use it directly without using an extra encoder ?
I see libx264 encoder in h264.py do encoding (H264Encoder._encode_frame) but I don't know how to override it.
Thank you

**Comment by jlaine** [comment]
@BloodyF You've hijacked an issue for your own purposes, you want to support some unnamed hardware decoder, and seem to be more at ease in c++. What exactly do you expect me to do?

**Comment by BloodyF** [comment]
> @BloodyF You've hijacked an issue for your own purposes, you want to support some unnamed hardware decoder, and seem to be more at ease in c++. What exactly do you expect me to do?
@jlaine ,
please guide me how to feed H264 bitstream directly to aiortc.
Because I don't need to get frame from v4l2 and encode frame
Thank you
