### ISSUE TITLE
Using aiortc without opus/vpx

### ISSUE THREAD

**Issue by lorenzo-arena** [aiortc/aiortc#1182]
I would like to use aiortc just for data channels in an embedded product (with Linux, but still with limited space); it there a way to avoid having a dependency on libopus and libvpx if I'm not planning on using media channels?

**Comment by R0NAM1** [comment]
I'd say no because it's a whole RealTime media library so they are required no matter what, but I'm pretty sure both compiled libraries are very small so it shouldn't be an issue, I don't have any issues with XFCE on 16gb of space. 
(Which should be your minimum for embedded systems nowadays anyways unless it's soldered.)

**Comment by lorenzo-arena** [comment]
In my case we're talking about *very* small systems (like ~500MB of max root fs size). For now I'll just use it like that, thanks anyway!
