### ISSUE TITLE
Mic and Speaker as MediaPlayer and MediaRecorder

### ISSUE THREAD

**Issue by adyanth** [aiortc/aiortc#161]
I am trying to implement this in a Raspberry Pi running debian stretch.
I tried with 'hw:1,0' as file with required options for channels, sample_rate and format as alsa, and 'plughw:1,0' for speaker. The usb audio card does not show any activity. Sometimes that it does, there is no proper audio in at least one direction.
The same thing works perfectly with an audio file. 
Can you help with setting the input and output?

**Comment by jlaine** [comment]
Show me some code at the very least..

**Comment by adyanth** [comment]
The server example, with VideoTransformTrack removed, along with cv2.
And, 
[code]
recorder = MediaRecorder('plughw:1,0', format='alsa', options={'channels': '1', 'sample_rate': '44000'})
player = MediaPlayer('hw:1,0', format='alsa', options={'channels': '1', 'sample_rate': '44000'})
[/code]

**Comment by jlaine** [comment]
If you're running a modified example could you paste the full diff? Otherwise if it's some entirely custom code, the full code would help.

Also as I don't have access to your hardware some additional tests would help:

- only change `player` or `recorder`, not both at once. What's the behaviour?

- try using ffmpeg on the command line. Does recording work? Does playback work?

**Comment by jlaine** [comment]
Closing, no reply from submitter
