### ISSUE TITLE
ValueError: packet is too long when trying to stream from v4l2 /dev/video*

### ISSUE THREAD

**Issue by hugobordigoni** [aiortc/aiortc#176]
Hi,
I'm very grateful for your work on this package!

I'm working on videostream-cli example and I face several issues when streaming from a device (on ubuntu through v4l2 /dev/video).

The only change I made from videostream-cli is to use this media player: `MediaPlayer('/dev/video0', format='v4l2', options={'framerate': '30', 'video_size': '1280x720'})`

I launched the answer with `python cli.py answer --signaling tcp-socket --record-to output/%06d.jpg`. After several seconds or few minutes (depending on the execution), it stops reading frame. Using verbose mode, I have a message saying that dtls goes in CLOSED state. I added this in rtcdtlstransport.RTCDtlsTransport.__run (line 492):
```
except Exception as e:
    import traceback
    traceback.print_exc()
```

So now, I see that it was interrupted because this exception was raised:
```
  File "[...]/pylibsrtp/__init__.py", line 200, in protect_rtcp
    return self.__process(packet, lib.srtp_protect_rtcp, SRTP_MAX_TRAILER_LEN)
  File "[...]/pylibsrtp/__init__.py", line 224, in __process
    raise ValueError('packet is too long')
ValueError: packet is too long
```
I can send the full traceback if it's useful.

When I run the answer in verbose mode, I see a lot of packets_lost. And every time the exception is raised, the number of packet loss is around 5000.

Also, I don't know if it's related but when I take a look at the images, the first ones are good, but approximately when there is the first packet loss, the images get completely broken.  [Example image](https://ibb.co/KrpY0hd)

And the quality is worst at each frame, it's never going back to normal. Like if there was no key frame at all.

**Comment by quito418** [comment]
Hi I am experiencing similar problems.

I came into 2 conclusions and trying to resolve the issue.

First, the image going wrong is because of packet loss in sending packets of 1 frame. (frame consists of lots of packets)
And if one frame goes wrong, the following frames goes wrong until the receiver gets a new key frame (you can check video tends to get better by changing the codec key frame interval to 1 second).

My conclusion now is 2 below

1. NACK has some issue. As RTP_HISTORY_SIZE in rtcrtpsender.py is small like 128, but receiver is sending nack for all missing packets where required histroy size is much bigger than 128, I think currently receiver is requesting retransmission of useless packets, and may forget retransmitting lost packet when frame size is bigger than 128 ( I did observed frame with 161 packets). 

2. Jitterbuffer, packet lost when input packet sequence number rotate 
I checked when packet sequence number turns from 65526 to 0, and jitterbuffer receives packet, the encoding result gets wrong. (I fixed the starting sequence of sending packet to 65500 and checked the encoding problem rise immediately)

I think we need fix in this parts

Thank you

**Comment by jlaine** [comment]
There seem to be three different issues in this ticket. I don't understand the first one, how did we end up with a packet's that too large?

The jitterbuffer one looks like a really bad one, this definitely needs a fix!

**Comment by quito418** [comment]
Hi jlaine,

I got that packet number '161' by using 30fps 1080x1920 video with target bitrate set to 3k using vp8. I suspect it would have been keyframe because other frames were about 8~30.
I was trying to increase the maximum target bitrate for my use.
I think this is out of scope.

My first conclusion was also about the NACKed packets which get cummulated in receiver side as video stream goes on which doesn't exist in the rtp_history in sender side. 
To reduce the retransmission packet amounts which can hurt the performance, should we limit the lost packets in NACK generator? 
I think lost packets in receiver side should be at least bounded by the rtp_history size in sender side.
Correct me if wrong!

Thank you for your fast response!

**Comment by hugobordigoni** [comment]
Hi @quito418, I also see the "rotation" of `packet.sequence_number`. Have you fixed it somewhere? I'll try to do so today, though I'm not familiar with the codebase. I'll give some update later.

Anyway, as you pointed @jlaine, it does not seem to be related with the first issue (the packet is too long exception, being raised).

**Comment by quito418** [comment]
Hi @hugobordigoni  
I don't have a well formated code now, because I am handling issues with decoder, receiver side

Below is  temporary solution in diff. Jitter buffer is used by rtcrtpreceiver.py, I added max_number input to use it for modular operation.

`11,13c11
<     def __init__(self, capacity, max_number, prefetch=0):
<         self.__max_number=max_number
<         assert self.__max_number >= capacity, "maximum number should be bigger than or equal capacity"
---
>     def __init__(self, capacity, prefetch=0):
27,29c25
<         elif packet.sequence_number <= (self._origin - MAX_MISORDER)%self.__max_number and (self._origin+self._capacity)%self.__m\
ax_number<  packet.sequence_number:
<             #print("[INFO][JitterBuffer] Received Seq:",packet.sequence_number,"In Origin" ,self._origin, 'packet seq',packet.seq\
uence_number, 'max_number of ',self.__max_number)
<             sleep(10)
---
>         elif packet.sequence_number <= self._origin - MAX_MISORDER:
32c28
<         elif packet.sequence_number < self._origin and (self._origin+self._capacity)%self.__max_number<  packet.sequence_number :
---
>         elif packet.sequence_number < self._origin:
34,35c30,31
<         #print("Pakcet Seq:",packet.sequence_number,"origin:",self._origin)
<         delta = (packet.sequence_number - self._origin)%self.__max_number
---
>
>         delta = packet.sequence_number - self._origin
39,40d34
<             #print("Jitbuffer overflow!! Income Packet:",packet.sequence_number,"Origin:",self._origin)
<             exit(1)
45,46d38
<             #print("Capacity overflow!! Income Packet:",packet.sequence_number,"Origin:",self._origin,"Capactiy",self.capacity,'d\
elta',delta)
<             exit(1)
94d85
<         self._origin= self._origin%self.__max_number
`

I found this working for now!

**Comment by hugobordigoni** [comment]
Thanks @quito418, the change looks good to me. Though, It does not solve any of the problem. We still have the packet is loo long exception and the images are still wrong. Does it solve it for you?

**Comment by quito418** [comment]
@hugobordigoni 

Hi, in my case I confirmed packets were being sent without loss  in sender side after the fix!

But I am resolving issue with NACK in receiver side, where loss is happening and frames are getting messed up.

I will update if I have a progress to share! 

FYI: I am using the same videostream-cli but not using the loopback device. I am using video file as inbut by using Mediaplayer as below

player = MediaPlayer('/home/mahi/bigbuckbunny.mp4')

**Comment by jlaine** [comment]
Could you submit an actual PR including a unit test please?

**Comment by quito418** [comment]
My code above is not robust enough and I am currently working on it, I will make a PR after more implementation and tests!
Thank you!

**Comment by AlexVestin** [comment]
@quito418 is there an update on this? I'm facing the same issue using v4l2 with the raspberry camera

**Comment by quito418** [comment]
@AlexVestin 

> @quito418 is there an update on this? I'm facing the same issue using v4l2 with the raspberry camera

Hi, I was able to solve the video decoding issue which was because of packet loss in decoder side, I wasn't able to reproduce "packet is too long". 

Sorry

**Comment by mschweig** [comment]
Hi, I am still having this issue on Raspi 4 with Ubuntu 20.04 with aiortc 0.9.28.

Is this not merged?

**Comment by borissedlak** [comment]
I just encountered the same for my stream, happens after roughly 1min and I could just fix it with passing on the ValueError in _send_rtcp
