### ISSUE TITLE
play sequential clips 

### ISSUE THREAD

**Issue by cdharris** [aiortc/aiortc#177]
I'm wondering if you can help point me in the right direction here.

I'm trying to modify the server example to play back clip, e.g. demo_instruct.wav, and then when that finishes, play back another clip.

Trying to change the clip player at all while the connection is established is resulting in the RTP stopping and I can't work out why.

Do you have any advice on how to play one clip, then another, then another, etc. ?

Thank you!

**Comment by cdharris** [comment]
for some further illustration, here's a snippit of a class inherited from VideoStreamTrack, that successfully plays one clip, and then cycles between blue and green frames forever after it finishes:

```python
    async def recv(self):
        pts, time_base = await self.next_timestamp()
        frame = None

        if self.clip_finished is False:
            try:
                frame = await self.next_clip_frame()
            except MediaStreamError:
                self.clip_finished = True
                self.clip_player.video.stop()

        if frame is None:
            frame = self.blank()

        frame.pts = pts
        frame.time_base = time_base
        self.counter += 1
        return frame

    async def next_clip_frame(self):
        if isinstance(self.clip_player, MediaPlayer):
            return await self.clip_player.video.recv()
        return None
        
    def blank(self):
        if (self.counter % 100) > 50:
            color = (0, 255, 0)
        else:
            color = (255, 0, 0)

        frame = VideoFrame.from_ndarray(
            numpy.hstack([self._create_rectangle(width=640, height=480, color=color),]), format="bgr24"
        )
        return frame
``` 

but whenever I set `self.clip_player = MediaPlayer(clip_path)` thereafter, I end up with `"Cannot send encrypted RTP, not connected"`

any pointers appreciated! thank you

**Comment by jlaine** [comment]
The exception you mention is unfortunate, it is almost certainly not the root cause of the problem. It can occur if the receiving code raises any kind of error. I need to improve this.

As for the core of your issue, I don't have a ready-to-use solution for you. It will indeed involve writing a custom stream track which act as a wrapper over multiple media players. You will however need to remap the timestamps so that they are consecutive.

Speaking of timestamps your code is doing something odd: `self.next_timestamp` is a helper which is useful for custom stream tracks which don't have their own notion of time. It basically sleeps in order to send out video frames at a regular pace. This makes sense when you are just sending blank frames. It does not however make sense when you are sending frames extracted from the MediaPlayer: these frames *already* have correct timestamps and are produced at the correct speed. Adding next_timestamp in this case is going to delay your video so that it is going to be sent at about half speed!
