### ISSUE TITLE
Dealing gracefully with disconnect

### ISSUE THREAD

**Issue by richlegrand** [aiortc/aiortc#225]
Hello, 
I'm noticing that at least with the webcam example, when you close the tab in the browser that's displaying the video, the server side python code seems unaware of the disconnect.   The _run_rtp task continues to run, frames are still being grabbed and encoded.  

I'm surprised that no exception is raised, but I can't seem to find an exception raised anywhere.  My goal is to be able to refresh the page and have the right things happen (reset state, connection, etc).  

I'm interested in your thoughts.

thanks!

**Comment by richlegrand** [comment]
It actually does get an exception after about 30 seconds.  It's initiated by a call into StunProtocol.connection_lost in ice.py, which signals 

result = await self._queue.get()

in Connection.recvfrom() by putting a null object on the queue, and when it sees the null object it raises a ConnectionError

We could put a timeout on the _queue.get().  I haven't seen it block for longer than 1.5 s.  But I don't know if this is a good solution or not -- I don't have much understanding of what's happening.  

I noticed that when you refresh the page (as opposed to closing it), the right things happen quickly.   A page refresh causes RTCDtlsTransport._recv_next() to raise a ConnectionError when lib.SSL_read() returns 0.  I would expect this same thing to happen when the page is closed, but things get blocked on the line  

                data = await self.transport._recv()

in _recv_next(), which eventually leads to Connection.recvfrom() described above.

Let me know your thoughts.

thanks!

**Comment by jlaine** [comment]
When you close a browser tab, the remote party is not informed that you have gone away: all WebRTC transport occurs over UDP, so there is no equivalent of a TCP socket close.

As you pointed out, you do eventually get an exception, because at the ICE level the periodic "consent checks" fail.

Putting a timeout on datagram reception is a non-starter, as I don't believe the specs mandate there has to be traffic between the peers to keep the RTCPeerConnection alive. Both peers could simply have muted their microphones.

You can however build your own solution without modifying aiortc. Some examples:

- you could have the client send periodic messages using datachannels and consider the connection dead if no message is received in X seconds

- you could have the client establish a WebSocket connection to the server. This connection will break when the tab is closed

- etc..
