### ISSUE TITLE
Ability to disable pyav

### ISSUE THREAD

**Issue by tmatth** [aiortc/aiortc#234]
We have maybe a specialized use case for aiortc, in that we use it for stress-testing webrtc servers. Ideally, we'd like to do this without actually encoding/decoding video, and if possible completely bypassing pyav (e.g., just sending dummy packets).

Is this a reasonable goal and would anyone else be interested?

**Comment by filips123** [comment]
WebRTC can also be used for non-video data translfer. For this, requiering `pyav` doesn't make sense, as it is not needed for this.

And as `pyav` requires `FFmpeg` and other system codecs, installation could be difficult, even if you won't actually use them. Because of that, `aiortc` should not require/force packages that are needed "just" for video transfer.

**Comment by jlaine** [comment]
This issue regularly crops up, but I just don't have time to maintain multiple favours of aiortc.
