### ISSUE TITLE
RTCPeerConnection.onicecandidate

### ISSUE THREAD

**Issue by ivelin** [aiortc/aiortc#246]
Is [this](https://github.com/aiortc/aiortc/blob/8354d3cac61fddeb0a5ee1a2eb5a8af48e737659/src/aiortc/rtcpeerconnection.py#L342) a good place to emit "onicecandidate" for compatibility with the [WebRTC JS spec](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidate)?

According to the [changelog](https://aiortc.readthedocs.io/en/latest/changelog.html):

> 0.7.0
> Peer connection
> Add RTCPeerConnection.addIceCandidate() method to handle trickled ICE candidates.

There is a [related discussion](https://github.com/aiortc/aiortc/issues/46) from about a year ago that was closed.

**Comment by jlaine** [comment]
No, that would not be the correct place to emit "icecandidate":

- the "icecandidate" event signals that the *local* peer has discovered a new local candidate

- `addIceCandidate` is about adding *remote* candidates

In practice, I'm not sure we need this event since `aiortc` gathers all candidates in one go, so you already have all the candidates in the offer / answer it generates.

**Comment by ivelin** [comment]
Yes, I was able to dig deeper and figure out the correct interfaces, thank you. 

I can confirm aiortc pairs well and trades bi-directional datachannel traffic with Chrome, Safari, Firefox, and Opera on desktop and mobile.

It takes 5-10 seconds to pair up a browser with an RPI running aiortc because of the full ICE scan. With trickle ICE the pairing feels instant between two browser instances. I know there is an open issue on this topic. Might be able to offer some help if you are planning to attack trickle ICE support in the near future.
