### ISSUE TITLE
Recording Janus Video room produces periodic aberations 

### ISSUE THREAD

**Issue by islandereleven** [aiortc/aiortc#335]
Hi everyone,

I am encountering an issue whilst recording a Videoroom from a remote Janus server with the [examples/janus](https://github.com/aiortc/aiortc/blob/master/examples/janus/janus.py) code.

The initial recorded frames are consistently crisp but the recording eventually gets broken and eventually recovers (probably when a key frame is received) to eventually break again in a cyclical fashion. I have put sample images from a recording on [imgur](https://imgur.com/a/DqaO0ze). From my meagre understanding of WebRTC it would seem like it might have something to do with key frames getting lost and the PLI not kicking in. 

Has any one encountered similar issues?

This should be reproducible using the following command below adapting the room and janus server (the same phenomenon can be observed recording to mp4 as well).

```python3 janus.py --room janus_room --record-to %09drecording.png janus_server_url```

**Comment by jlaine** [comment]
`aiortc` has the code to send a PLI (Picture Loss Indication), see `RTCRtpReceiver._send_rtcp_pli`

However I haven't had a chance to write the code which *triggers* sending it, so you are right, the image stays broken until the next keyframe. It's been a while since I dived into that part of the code, could you try poking around WebRTC specs and / or implementations to see under what condition we should be sending PLI?

**Comment by islandereleven** [comment]
Ah ok, that's good to know. Thanks for the swift answer. 

I'll look up what needs to be done then.

**Comment by jlaine** [comment]
I had forgotten but sending PLI is already tracked by issue #58 let's continue the discussion there.
