### ISSUE TITLE
RTCIceCandidate API does not match WebRTC spec

### ISSUE THREAD

**Issue by jmgurney** [aiortc/aiortc#342]
In attempted to get ICE working on a system, I did what JS does wrt adding an ICE candidate in my python code.  The issue is that the expected args to the Python code: https://aiortc.readthedocs.io/en/latest/api.html#aiortc.RTCIceCandidate does not match the spec: https://w3c.github.io/webrtc-pc/#constructor-0 .  Notice how at step 3, the args are:  candidate, sdpMid, sdpMLineIndex, usernameFragment, yet the aiortc docs list the following args as required: component, foundation, ip, port, priority, protocol, type.

It looks like the python code expect the user to parse out the candidate string manually.  The issue is that the documentation does not say this, nor does it provide a proper mapping between the grammar as defined here: https://tools.ietf.org/html/rfc5245#section-15.1 and the required arguments.

In looking at the examples, I cannot see one example that interacts w/ a browser, they all interact w/ aiortc code only:
```
(aiortc.test) nmac,ttys020,/tmp/aiortc.test/src/aiortc/examples,610$ls $(grep -rl RTCIceCand * | sed -e 's:/.*::')
apprtc:
README.rst	apprtc.py	photo.jpg

datachannel-cli:
README.rst	cli.py

datachannel-filexfer:
README.rst	filexfer.py

datachannel-vpn:
README.rst	tuntap.py	vpn.py

videostream-cli:
README.rst	cli.py
```
Notice that there is no JS files in any of them, so there is no example for me to follow when interfacing w/ a browser client.

Please update the API to properly match the WebRTC spec.

**Comment by jmgurney** [comment]
Simple wrapper that matches the WebRTC api except for usernameFragment:
```
# Implement https://w3c.github.io/webrtc-pc/#constructor-0 per the
# spec.
from aioice.candidate import Candidate
from aiortc.rtcicetransport import candidate_from_aioice
def RealRTCIceCandidate(candidateInitDict):
        candpref = 'candidate:'
        candstr = candidateInitDict['candidate']
        if not candstr.startswith(candpref):
                raise ValueError('does not start with proper string')
        candstr = candstr[len(candpref):]
        cand = Candidate.from_sdp(candstr)

        ric = candidate_from_aioice(cand)
        ric.sdpMid = candidateInitDict['sdpMid']
        ric.sdpMLineIndex = candidateInitDict['sdpMLineIndex']
        # XXX - exists as part of RTCIceParameters
        #ric.usernameFragment = candidateInitDict['usernameFragment']

        return ric
```

**Comment by jlaine** [comment]
Instead of demanding I do some free work for you, could you explain why this matters? Sure the constructor does not match the JS one, but aiortc's ICE candidates carry all the relevant information.

For most scenarios you'll just be passing the offer/answer SDP to RTCPeerConnection which will take care of creating the `RTCIceCandidate` instances. If for some reason you want to parse the SDP yourself you can always use `aiortc.sdp.candidate_from_sdp`.

> In looking at the examples, I cannot see one example that interacts w/ a browser, they all interact w/ aiortc code only

Look a bit harder: https://github.com/aiortc/aiortc/tree/master/examples/server

**Comment by jmgurney** [comment]
A) that you took this as a demand for work is sad, it is a bug, IMO, and so I filed it.  If you consider bug reports a demand that your code be fixed, I can't help that.
B) I even provided sample code so saying I demanded free work is BS. I actually did most of the work for you.  Do you want a unit test for it?  I could have provided it. 
C) It maters because you CLAIM to follow the WebRTC spec, but don't document when you don't.

Now if you had asked for me to do parts of the work to complete it, I might have, but since you feel that you don't want the help, guess no need to help you w/ my free labor either.
 
And I did look, in the server case, the only ICE references is the server code is:
```
    @pc.on("iceconnectionstatechange")
    async def on_iceconnectionstatechange():
        log_info("ICE connection state is %s", pc.iceConnectionState)
        if pc.iceConnectionState == "failed":
            await pc.close()
            pcs.discard(pc)
```
which doesn't call RTCIceCandidate in neither the server nor client portions of it.  So, I don't see how/where the ICE candidates are added to the server side of things.

**Comment by jlaine** [comment]
The WebRTC specs specify a JavaScript API. As we're using a different language, there will always be some level of adaptation necessary. In this case, I ensured that the member variables of `RTCIceCandidate` are named the same as in the JS API, so that you have access to the same information. You are correct that the constructor differs, but again, I'd be keen to understand how this restricts you in your usage.

Regarding the `server` example, ICE candidates are created and added by the calls to `pc.setRemoteDescription`:

- server side: https://github.com/aiortc/aiortc/blob/fd3b47d4cd0d308aadeafcee7c12745332929bec/examples/server/server.py#L155

- client side: https://github.com/aiortc/aiortc/blob/master/examples/server/client.js#L99

This is a very typical usecase: you pass the offer / answer SDP to the `RTCPeerConnection`, which takes care of parsing the SDP, creating `RTCIceCandidate` instances and passing them to the ICE stack. In this context, the exact signature of the `RTCIceCanidate` constructor is very much an internal implementation detail.
