### ISSUE TITLE
Data Channel transfer rates are a bit low

### ISSUE THREAD

**Issue by steveseguin** [aiortc/aiortc#36]
Data Channel transfer rates are somewhat low, even when sending locally on the same machine.

Using the _datachannel-filexfer_ example to send a compressed 64-megabyte file, it takes about 90 to 120-seconds. I suppose that is about 5-mbps. A chrome-to-chrome local implementation with the same file is about 45-mbps. ie) **https://webrtc.github.io/samples/src/content/datachannel/filetransfer/**

My goal is to offer a hosted quality-of-service webRTC-focused speed test, offering insights into maximum webRTC UDP connection speeds and packet loss information with both upload and download. I do not yet understand how I might be able to access connection analytics, but I suppose perhaps aiortc is not the ideal solution for what I am trying to do anyways?  Either way, I am loving what I am seeing so far regardless. This is Fantastic stuff!

**Comment by jlaine** [comment]
Yes I'm aware the Data Channels implementation is not optimized speed wise. I did some testing of my own and:

- there is some room for improvement in the SCTP stack, especially on the receiver side. Have you tried a aiortc to Chrome transfer?

- using uvloop also gives some gains too

- the speed probably won't reach full parity with the browser's C/C++ implementationd

If you have the time / skill to dig further, I would be happy to review pull requests.

**Comment by jlaine** [comment]
I have made some changes to the way data is buffered in 71b3349472f8dc38a63063f81f101c06fff38e81, and for a local transfer the speeds went from 22MBps to 33MBps. I'll keep profiling and see if we can do better.

**Comment by jlaine** [comment]
@steveseguin could you give the datachannel-filexfer example anothere go using the latest code on `master` and report back?

**Comment by steveseguin** [comment]
Will do next chance I get. Thanks!!

I did try the alternative asyncio option and got a modest boost with that
too.

**Comment by jlaine** [comment]
I have made a lot of improvement to the SCTP congestion handling, the aiortc implementation was way off spec.

For a real-world test on my local WiFi network I'm seeing ~ 4x improvements using `datachannel-filexfer`!

The phony "perfect network" scenario (i.e. loopback on the same machine) scenario has also improved. Using the latest code with Python 3.7 I'm consistently exceeding 40MBps.

**Comment by jlaine** [comment]
In light of the improvements in version 0.9.2 I'm going to close this issue, but feel free to comment or re-open if you do not agree with the results.

**Comment by steveseguin** [comment]
One of my colleagues has taken another stab at this codebase for me and the results are pretty fantastic. Thank you!

**Comment by jlaine** [comment]
Cool! If you need to go further performance-wise, I'm pretty sure the code which handles reassembly can be improved. However I don't have the need or the time for it right now

**Comment by sfrost23** [comment]
First of all, thanks for the awesome package. It's the fastest usable implementation of webrtc I've seen so far (it beats the go version in my tests).

That being said I'm still trying to improve the bandwidth so that it can scale. At the moment I can see 60mbps with one client, but if I have 10 clients then each one gets 6mbps. What bottlenecks can be removed to increase the ceiling? Can you point a bit closer to the code that can be optimized/compiled into a native extension to make it faster?

In a similar vein, what can be done to reduce the cpu usage of the process? Taking 100% cpu for 60mbps is a bit high (that's with a localhost transfer). I'd like to reduce it significantly so that disk i/o is the bottleneck and not cpu.

**Comment by jlaine** [comment]
I'm really glad you find aiortc easy to use, that is the primary design goal!

So far my profiling hasn't turned up an obvious area of code for optimization, I suggest you do some profiling of your own as I am not an expert on performance yet. I'd really love some input on this.

As for scaling, I think at some point you will need your application to switch to a multi-process design (for instance sharding N users per process). Only one block of pure-python code can be running at any given time - so unless you switch to multiple processes you'll be bound to the performance of a single CPU core.

**Comment by inactivist** [comment]
I'll be dealing with this issue soon, as my current implementation suffers from similar problems.  I'll be experimenting with multi-process approaches, and will share my experience here.

**Comment by jlaine** [comment]
I think multi-process and optimization are two different topics:

- once candidates for optimization are identified they can be performed in aiortc itself

- multi-process on the other hand would really apply to the target app as it's highly dependent on what you are doing. I'd be quite happy to include a multi-process example of course.

**Comment by inactivist** [comment]
> * I'd be quite happy to include a multi-process example of course.

Examples always appreciated.   Main thing I'm looking for is to be able to process cpu- bound operations independently on the datachannel.send() without blocking the receiving thread (loop).  (I'm pulling data from a network feed, then sending it along via datachannel.send())

**Comment by sfrost23** [comment]
Multiprocessing will definitely alleviate the issue but I do think optimization is paramount at this stage. In my testing I was able to increase the throughput to 240mbps on a 4c/8t server but this made the system borderline unusable otherwise (all cores pegged at 100%) so it's not practical. I'm also trying to understand why the performance isn't scaling linearly with the number of cores (e.g. I'd expect 480mbps in my testing) but this just may be multiprocessing overhead.

- Here are some handy flame charts that will help with optimization (generated with [py-spy](https://github.com/benfred/py-spy))

Functions
[![Functions](https://raw.githubusercontent.com/sfrost23/aiortc/346b33106a4d25a5e8bbc484ce80aaac83979ef8/profile_funcs.svg?sanitize=true)](https://cdn.jsdelivr.net/gh/sfrost23/aiortc@patch-1/profile_funcs.svg)

Functions w/ line num
[![Functions w/ line num](https://raw.githubusercontent.com/sfrost23/aiortc/f5c74ec8211e21b1adb7040cbdeb9f63af69cfcd/profile_funcs_linenum.svg?sanitize=true)](https://cdn.jsdelivr.net/gh/sfrost23/aiortc@patch-2/profile_funcs_linenum.svg)

I think the _transmit function is a good parent to start optimizing from. It looks like the `__bytes__` methods of the `Packet` and `Chunk` classes of rtcsctptransport.py are quite heavy. Maybe we could use ctypes for this? I think it's slow due to the copying and manipulating (struct.pack) of all those bytes objects. Ideally we could do all this packet generation in a C library.

- Can you explain the `aiortc.rtcsctptransport.MAX_OUTBOUND_QUEUE` constant? In my testing increasing this value produced much better throughput on a higher latency link (80ms). I mean a 3-4x increase which got close to saturating the link. I'm guessing having a higher value will decrease the number of round-trip messages (which is tied to the bandwidth-delay product). However, it noticeably decreased the localhost throughput (~20%). Why would that be?

Also, enabling logging has a noticeable performance hit. I stubbed out `RTCSctpTransport.__log_debug` for a free 8%!

**Comment by jlaine** [comment]
Hi @sfrost23 thanks for all the data it will take me a little while to process it.

I have spend a fair chunk of the day doing some profiling of my own. Some takeaways:

- Python 3.7 is the best Python to date with respect to asyncio performance

- uvloop still gives a noticeable gain, especially combined with a minor change to aioice: 

https://github.com/jlaine/aioice/blob/9ef27a009c23349f259c7e53dccda8974534a01c/aioice/ice.py#L771
 
Replace by:

`loop.call_soon_threadsafe(self._queue.put_nowait, (data, component))`

I need to dig a bit more to check performance is no worse without uvloop.

- timers in asyncio seem to come at a cost. For data transfers we are constantly starting / stopping / restarting the T3 timer according to spec, maybe we can collapse some of these operations

- cProfile based profiling doesn't seem to tell the whole picture, I don't seem to see any time spent in the C code

- I concur concerning logging. I pushed out an update to aioice which prunes two debug statements. Concerning aiortc's logging I'm not sure what to do, as it is hugely useful for debugging.. suggestions?

- The crc32c implementation may not be the best. On Intel processors I get performance gains by installing `crc32c` and using:

`from crc32c import crc32` (using latest aiortc's git code)

If the performance *without SSE* is in line with that of crcmod I'll probably switch to it.

- Parsing / serialization: I'm not too enthusiastic about switching to C, but might consider Cython.

- Serialization: I think even in pure Python we can do better by serializing into a preallocated buffer (pack_into) instead of concatenating so much.

Anyway, adding all these bits together I passed the 100Mbps mark using the `datachannel-filexfer` on a 256MB file on the loopback interface on my laptop. One core maxed out sending, one at ~ 90% receiving.

**Comment by inactivist** [comment]
> * I'm not too enthusiastic about switching to C, but might consider Cython.

Have you considered [pybind11](https://pybind11.readthedocs.io/en/master/) / [cppimport](https://pybind11.readthedocs.io/en/master/compiling.html#building-with-cppimport)?

**Comment by jlaine** [comment]
> Nit: To keep this pypy-compatible (if it is?), I'd prefer cffi.

Unfortunately PyAV isn't pypy-compatible, I've repeatedly tried to make it so but cannot understand the crash. The rest of the code is pypy compatible. Also: Cython is pypy-compatible so it doesn't introduce any additional incompatibility.

**Comment by inactivist** [comment]
> Cython is pypy-compatible so it doesn't introduce any additional incompatibility.

Ah.  I hadn't considered that.  Thanks.

**Comment by jlaine** [comment]
@sfrost23 could you re-run your tests with the latest git code after installing `crc32c` and the latest `aioice` version? The `__bytes__` methods still suck, but I'm still seeing significant improvements.

**Comment by sfrost23** [comment]
Hey @jlaine, good stuff! I'm able to replicate your results (saw about 106mbps in my test). Now, if we can get it to saturate a 1gbps link on a modern server I'd be willing to call it a day ;)

Hmm, do those numbers match up with the results from the profiler? It definitely looked like `__bytes__` takes much more cpu time than that. I've convinced myself that cythonizing the hot code is the right way to go. I took a stab at implementing the `Packet`class, it doesn't improve the performance.. yet, but I think that's because the `Chunk` classes need to be cythonized as well. Or this could be a red herring and not the right place to optimize.

Initial attempt, this took a few hours of debugging bizarre failure modes with print statements.
```
cdef class Packet:

    cdef char* data
    cdef view.array pydata
    cdef public unsigned short source_port
    cdef public unsigned short destination_port
    cdef public unsigned int verification_tag
    cdef public list chunks

    def __init__(self, unsigned short source_port, unsigned short destination_port, unsigned int verification_tag, list chunks):
        self.source_port = source_port
        self.destination_port = destination_port
        self.verification_tag = verification_tag
        self.chunks = chunks

    def __cinit__(self):
        self.data = <char *>PyMem_Malloc(2048)
        self.pydata = view.array(shape=(2048,), itemsize=sizeof(char), format="c", allocate_buffer=False)
        self.pydata.data = <char *> self.data
        self.pydata.callback_free_data = PyMem_Free

    cdef bytes _c_bytes(self):
        header = pack(
            '!HHLL',
            self.source_port,
            self.destination_port,
            self.verification_tag,
            0)

        self.pydata[:len(header)] = header

        cdef bytes chunk_bytes
        cdef unsigned int count = len(header)
        cdef unsigned int chunk_size

        for chunk in self.chunks:
            chunk_bytes = bytes(chunk)
            chunk_size = len(chunk_bytes)
            self.pydata[count:count+chunk_size] = chunk_bytes
            count += chunk_size

        checksum = crc32(self.pydata[:count])
        checksum = pack('<L', checksum)
        self.pydata[8:12] = checksum
        return bytes(self.pydata[:count])

    def __bytes__(self):
        return self._c_bytes()

    @classmethod
    def parse(cls, data):
        if len(data) < 12:
            raise ValueError('SCTP packet length is less than 12 bytes')

        source_port, destination_port, verification_tag = unpack_from('!HHL', data)
        checksum = unpack_from('<L', data, 8)[0]

        # verify checksum
        check_data = data[0:8] + b'\x00\x00\x00\x00' + data[12:]
        if checksum != crc32(check_data):
            raise ValueError('SCTP packet has invalid checksum')

        packet = cls(
            source_port=source_port,
            destination_port=destination_port,
            verification_tag=verification_tag,
            chunks=[])

        pos = 12
        while pos <= len(data) - 4:
            chunk_type, chunk_flags, chunk_length = unpack_from('!BBH', data, pos)
            chunk_body = data[pos + 4:pos + chunk_length]
            chunk_cls = CHUNK_TYPES.get(chunk_type)
            if chunk_cls:
                packet.chunks.append(chunk_cls(
                    flags=chunk_flags,
                    body=chunk_body))
            pos += chunk_length + padl(chunk_length)
        return packet

```

**Comment by lgrahl** [comment]
Be aware that browsers using usrsctp (read: all of them) are CPU capped (one core) using an i7 5820k at around 400 Mbit/s. RAWRTC roughly achieves 500 Mbit/s. So, if you can reach that in Python, hats off. :slightly_smiling_face: 

By that I'm saying: I'm quite certain that [usrsctp has some performance issues](https://github.com/sctplab/usrsctp/issues/245) but it will be hard (if not impossible) to reach 1 Gbit/s in pure Python.

**Comment by sfrost23** [comment]
That's a fair point, but I'm thinking 1 Gbps aggregate, and not necessarily to one client. I'm looking at it as if I were trying to optimize a UDP server (which I think should be possible with Python).

**Comment by inactivist** [comment]
> That's a fair point, but I'm thinking 1 Gbps aggregate, and not necessarily to one client. I'm looking at it as if I were trying to optimize a UDP server (which I think should be possible with Python).

This is my use case - multiple clients (peers) receiving real-time data streams from the aiortc server, on an isolated network.  Unfortunately I'm out of town this week and won't be able to do much code diving / profiling right now =(

**Comment by lgrahl** [comment]
You still have the GIL unless you want to fire up multiple processes running separate event loops. :slightly_smiling_face: But enough off-topic from my side. Just wanted to make you aware.

**Comment by jlaine** [comment]
I made a one-line change to `aioice` which had a fairly large impact (~10%) on the performance when running the `datachannel-filexfer` example:

https://github.com/jlaine/aioice/commit/b5f49b86963b6f902415f51ff5b537a342b68797

With `aioice` version 0.6.12 and the latest `aiortc` git code, using uvloop I get:

```
$ python examples/datachannel-filexfer/filexfer.py -s unix-socket receive /dev/null
received 268435456 bytes in 17.8 s (120.354 Mbps)
```

**Comment by sfrost23** [comment]
That's excellent! I noticed how there was quite a bit of time being spent in sendto but wasn't sure what to do about it.

On my end I've been able to see a ~12% improvement from the git code after converting `Packet` and all the `Chunk` classes to cython classes. A lot of time is wasted setting up and tearing down python objects, so using native types for repeatedly called functions will see a performance boost. There are still some more areas I'd like to optimize, but once I'm done I can create a PR if you like? I'm doing this without any real understanding of the underlying protocol, so if there are some higher level design changes you can see to improve performance that would help too.

All these little optimizations are definitely adding up!

**Comment by jlaine** [comment]
Cythonizing all chunk classes is a waste of time, the only two on the hot path are DataChunk and SackChunk. At this stage I'm not 100% convinced cythonizing parsing / serialization is worth the loss in readability + tooling headache so I'd need a bit of convincing. To get comparable numbers, what's your speed with and without the cythonization on the latest git code?

**Comment by lgrahl** [comment]
When we're already at optimisations, you may want to try `__slots__` on the `Chunk` class.

**Comment by jlaine** [comment]
> When we're already at optimisations, you may want to try `__slots__` on the `Chunk` class.

I gave that a try but in my tests it degraded performance, I think this is a memory optimization but not a speed optimization.

I landed another round of optimizations which gets rid of the `Packet` class altogether in favour of `parse_packet` and `serialize_packet` functions. I'm currently reliably hitting 140 Mbps, still with no C or Cython code.

**Comment by jlaine** [comment]
Experience from other projects tells me it's not as simple as that to make a Cython-based project distributable, see:

https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules

The problem stems from the fact Python's package manager has no declarative dependencies, so it doesn't know that you need Cython until it executes `setup.py`.. which requires Cython. To try it out yourself, in a clean virtualenv try to `pip install -e /path/to/your/patched/aiortc`. I'm going to put this issue on hold for a bit, I've spent a lot of time on it and need to get back to paid work.

**Comment by sfrost23** [comment]
That's quite strange, I wonder what it could be attributed to (I am running on OS X).

In any case, I'm able to exceed 500Mbps by multiprocessing with 4 cores while leaving ample resources for the rest of the system, so I can probably run with this for now. 

I'm still trying to understand the `MAX_OUTBOUND_QUEUE` constant https://github.com/jlaine/aiortc/issues/36#issuecomment-451778134 and its effect on higher latency links. Can you explain the effect of decreasing/increasing it?

This was a fun sprint! 🙂

**Comment by jlaine** [comment]
You are right that `MAX_OUTBOUND_QUEUE` needs investigating so here are some explanations.

The `outbound_queue` variable's name is a bit misleading as it contains both data chunks which are in flight (indices < `outbound_queue_pos`) and chunks which are ready for transmission (indices >= `outbound_queue_pos`). I believe usrsctp uses two distinct queues, but I wanted to avoid popping / pushing chunks every single time we transmit a chunk.

`MAX_OUTBOUND_QUEUE` was added to avoid having huge amounts of data getting sucked in from the upper layer (data channels) into the SCTP transmission buffer, as performance will break down since we frequently run over the `outbound_queue` when processing incoming SACKs. However, you are right it is arbitrary since it caps both the amount of in-flight data (which *should* already be governed by congestion avoidance / slow start) and the amount of data which is chunked for future transmissions.

I would suggest you experiment with capping the size of outbound queue by something like:

`while len(self._outbound_queue) < self._outbound_queue_pos + SOME_AMOUNT`

We might find out that congestion avoidance is not properly implemented..

**Comment by sfrost23** [comment]
I've been experimenting with `MAX_OUTBOUND_QUEUE` and capping the length of `self._outbound_queue`, I have some observations but not I'm really sure how to change the behavior.

With the default `MAX_OUTBOUND_QUEUE` of 100 I see consistent/stable throughput albeit it is nowhere close to saturating the link. If I adjust this to be much larger (500 or 1000) then I see the throughput steadily climb until it saturates the link before dropping precipitously (like a sawtooth wave) - this pattern repeats in a cycle. I also noticed in my traffic counters that the link sent much more data than was received (e.g. my driver says I sent 1.3GB for a 1GB file, the overhead is significantly lower for the default case). However, despite the constant rise and fall and extra data sent, the average transfer rate is higher than the default.

I tried capping it with `self._outbound_queue_pos + SOME_AMOUNT` as well but I see the same pattern even with a value of 1.

**Comment by jlaine** [comment]
The drops you report sound like you eventually start getting T3 timeouts, which put you back into slow start mode. As stated previously it would probably warrant an investigation into whether I properly implemented congestion avoidance.

**Comment by jlaine** [comment]
In the branch of code you are looking at, you are experiencing packet loss: the remote party is acknowledging data, but with "gaps". When a TSN reaches 3 "misses" (i.e. the remote party has acknowledged later TSNs 3 times, without acknowledging this TSN) you may enter fast retransmit:

https://tools.ietf.org/html/rfc4960#section-7.2.4

The conditional you asked about was only added recently to "give up" on chunks when using partial reliability (using maxRetransmits or maxPacketLifeTime). If you're in the business of transferring files, this doesn't concern you (partial reliability would make no sense) so `_maybe_abandon` will always return false.

My understanding is that T3 expiry is not the "happy" way to recover from packet loss, it's a fairly harsh last resort solution where you:

- give up on any data which has been transmitted beyond the cumulative ACK point, and reschedule it all for retransmission
- reset the congestion window to a single MTU

More info:

https://tools.ietf.org/html/rfc4960#section-6.3.3

If you're going to continue work on performance, you're definitely going to have to read the RFC in full. Good luck, it's not trivial!

**Comment by sfrost23** [comment]
Well, I've gone down the rabbit hole of benchmarking various congestion algorithms with iperf. I've found that aiortc's implementation performs similarly to the stock linux congestion control algorithm (cubic) on long fat networks (LFNs). However, google's BBR algorithm is _mindbogglingly_ faster in terms of performance without much packet loss at all (2-3x increase). If I go down this road maybe it would be better to rip out this algorithm entirely (which was mostly conceived in the 90s) and replace it with something modern like BBR? https://tools.ietf.org/id/draft-cardwell-iccrg-bbr-congestion-control-00.html#rfc.section.1

**Comment by sfrost23** [comment]
Hehe of course.  What I'm proposing wouldn't break compatibility with any browsers. BBR is simply a congestion control algorithm which is model-based instead of being packet loss based like all other existing implementations (all it's doing is changing cwnd and adjusting the packet rate), and as such can be implemented with SCTP. The result is essentially a huge leap forward in terms of bandwidth saturation on higher latency links (100ms). It's also entirely sender based, so the receiver doesn't need to change their congestion control algo.

Looks like it's been done with SCTP: https://groups.google.com/forum/#!topic/bbr-dev/3o9iK72srTw

Probably out of scope, but definitely very interesting 🙂

**Comment by lgrahl** [comment]
@juliusf analysed behaviour of SCTP+BBR and RTP on the same link (correct me if I'm wrong). I'm not sure his work is released, yet but he may be able to share some insights. :slightly_smiling_face:
@weinrank and @tuexen may also be able to share their experience with SCTP's CC.

Anyhow, an actual live implementation of SCTP+BBR would be very interesting indeed. IMHO aiortc would be the perfect candidate for prototyping since it's easy to hack on.

**Comment by jlaine** [comment]
I have found fixed a number of issues I found in the code, which were hurting real-world performance, but didn't crop up in loopback-only testing.

- the cwnd (congestion window) was being raised even when not fully utilized feb973a33097364724e238f12b14183675d7b136
- the fast recovery exit point was too "early" 1e81150172ed880d6328b1f914ad9171982f3b9b
- the Highest TSN Newly Acknowledge logic (used to enter fast recovery) was wrong d5a2cdd287ebf393efa25f85a4205e9517db3d52
- the MAX_OUTBOUND_QUEUE value was in effect limiting the cwnd to 120kB which is insufficient for high bandwidth * latency links a686073405079db9dc32c655d9f0f0431e8b4f50

My real-world testing between an AWS instance and my laptop (WiFi + DSL) shows a 2x improvement. The "loopback" phony scenario gets a (small) penalty, but I'm not sure we care.

**Comment by jlaine** [comment]
I'm going to close this issue, the transfer rates are definitly not "low" anymore.

Furthermore, some pending changes to uvloop should get us even better performance see:

https://github.com/MagicStack/uvloop/pull/238#issuecomment-474136782
