### ISSUE TITLE
Several examples broken when used against aiortc 0.9.28

### ISSUE THREAD

**Issue by alexbird** [aiortc/aiortc#368]
tl;dr I think you might need to ship new binaries to pip

The commit https://github.com/aiortc/aiortc/commit/31abde4c7f142527a2a59c76333aafe627d4b2c6 updates the example code. 

The example README files suggest installing dependencies via pip. When I run the example code from github against the pip installed library, the extra `await` trips it up.

If the examples are installed by pip somewhere, then my assumptions are all wrong! But I can't see them anywhere.

**Comment by jlaine** [comment]
This is not a question of binary wheels or source. It's indeed that you need to use examples which match your `aiortc` version: if you are using aiortc 0.9.28 (the latest one on PyPI), you need to use the examples from the `0.9.28` tag.

I've held up on releasing `1.0.0` because I wanted to group together several breaking changes, but maybe I should just go with it and move to `2.0.0` on the next breaking change..

**Comment by alexbird** [comment]
You are right, of course. 

It's tricky to know how much to hold peoples hand. IMO the example README starts out at a beginner level, giving the pip command line, so perhaps it should also hint that they need to get example code from the matching tag. 

And thanks, this looks epic. I've been working with WebRTC's C++ for a couple of weeks and have been regretting my life choices.

**Comment by jlaine** [comment]
aiortc 1.0.0 was released in October 2020, fixing this issue.
