### ISSUE TITLE
[icetransport] Status not updated

### ISSUE THREAD

**Issue by Laityned** [aiortc/aiortc#469]
If consent is lost after that the DTLS is shutdown by the remote party, the status of rtcicetransport is never updated to closed or failed. This result in not able to detect the closed peer connenction

To reproduce this issue use example webcam.py

add to client.js on the second row:
`
window.onbeforeunload = function() {
  if (pc !== null) {
    pc.close();
  }
};
`
Close the browser tab while camera view is visible

**Comment by jlaine** [comment]
OK I tested this and there is indeed a problem here. Currently, the only way `RTCIceTransport` changes to the `failed` state is when a call to `_recv()` or `_send()` fails. This is fine so long as there is a running RTCDtlsTransport, because it calls `_recv()` in a loop.

However if the DTLS layer has shutdown cleanly, there are no more calls to `_recv()` (or `_send()`), so the status change is not reported. As a result, the peer connection's `iceConnectionState` and `connectionState` don't change either.

**Comment by jlaine** [comment]
OK I have a work-in-progress PRs:

- for aioice here: https://github.com/aiortc/aioice/pull/44
- for aiortc here: https://github.com/aiortc/aiortc/pull/472

**Comment by Laityned** [comment]
Thank you
