### ISSUE TITLE
How to limit `aiortc` media server ports?

### ISSUE THREAD

**Issue by mmoallemi99** [aiortc/aiortc#487]
Hi everyone,

I'm using `aiortc` for a video streaming platform and I want to deploy my application inside a docker container, so I wanted to know how can I limit the ports to a range and just open those ports for the container?

Thanks in advance

**Comment by jlaine** [comment]
You cannot limit the UDP ports used by ICE, they are picked randomly by the OS:

https://github.com/aiortc/aioice/blob/c71c3afe064a028a8f39bde45c95897dbbaba35f/src/aioice/ice.py#L842

**Comment by ekalosak** [comment]
I'm not sure I understand, @jlaine - wouldn't this require an aiortc server to open all ports?

**Comment by ekalosak** [comment]
To connect the dots for the next wayward programmer who lands here, that link to the `loop.create_datagram_endpoint` answers the question sufficiently because it shows the function being called with a local_addr having port 0. Port 0 is reserved for "assign me a random open port" in BSD, see e.g. `socket_bind` in http://web.mit.edu/macdev/Development/MITSupportLib/SocketsLib/Documentation/sockets.html
