### ISSUE TITLE
extract raw RTP packets

### ISSUE THREAD

**Issue by jmyth742** [aiortc/aiortc#550]
Hi,
*Not and Issue exactly* 
I am working with your lovely framework. I looked through the code etc and i cannot seem to see if this is possible, so i thought i would ask. When connecting to a webRTC stream, i would like to consume the raw RTP packets. 

I see you do the handling of the RTP and RTCP under the hood. I would not want to change this, but i am wondering if you offer any exposure to these packets through the framework?

Any help or suggestions to do this in the least invasive way possible would be amazing...thanks!

Jonny

**Comment by jlaine** [comment]
Hi Jonny,

If you use RTCPeerConnection, aiortc is going to set up and RTCRtpReceiver which will consume the RTP packets.

If you want to handle this yourself, your best bit is probably to construct the RTCIceGatherer / RTCIceTransport / RTCDtlsTransport yourself, and slightly monkey-patch RTCDtlsTransport so that it hands you the raw data.

There is a demo of this here:

https://github.com/jlaine/aiortc-wpt-demo/blob/781ddddc6b78574b57f2ac0db9ec935dea70d067/demo.py#L44

**Comment by jmyth742** [comment]
Hey @jlaine ,

Ok, just for clarity:
i see the RTCPeerConnection handles all this and consumes the RTP packets, however with this approach there is no possiblity for me to directly consume these rtp packets and say for example, forward these packets to another endpoint? 

Next point, you suggest i could manually go through above steps for establishing a connection to a stream then monkey-patch the RTCDtlsTransport and extract these raw packets that way?  Sorry, dont want to seem like im double asking you, just want to make sure i am clear :) 

Again thanks for the response!! legend!!

**Comment by jlaine** [comment]
You can indeed use an `RTCPeerConnection` and still monkey-patch the `RTCDtlsTransport`, though the timing will be a little trickier: the DTLS transport will only be created once `setLocalDescription` and/or `setRemoteDescription` have been called.

To get hold of the DTLS transport you can use `RTCPeerConnection.getReceivers()` then use the `RTCRtpReceiver.transport` attribute which is the `RTCDtlsTransport` instance.
