### ISSUE TITLE
The example cli.py not working for mp4 file with audio

### ISSUE THREAD

**Issue by chuan-chu** [aiortc/aiortc#778]
Tried two instances of cli.ly with the offer reading from .mp4 video:
instance 1: python cli.py offer -s tcp-socket --play-from <file>.mp4 ...
instance 2: python cli.py answer -s tcp-socket ...
Both hold there after diplaying "Receiving video..." and "Receiving audio..."

But if I comment out the line to add audio track, working OK.
I tested it on Windows 11 platform

When logged in file, found one warning message:

WARNING:aiortc.rtcdtlstransport:RTCDtlsTransport(server) Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\aiortc\rtcdtlstransport.py", line 531, in __run
    await self._recv_next()
  File "C:\Program Files\Python39\lib\site-packages\aiortc\rtcdtlstransport.py", line 630, in _recv_next
    await self._handle_rtp_data(data, arrival_time_ms=arrival_time_ms)
  File "C:\Program Files\Python39\lib\site-packages\aiortc\rtcdtlstransport.py", line 575, in _handle_rtp_data
    packet = RtpPacket.parse(data, self._rtp_header_extensions_map)
  File "C:\Program Files\Python39\lib\site-packages\aiortc\rtp.py", line 710, in parse
    packet.extensions = extensions_map.get(extension_profile, extension_value)
  File "C:\Program Files\Python39\lib\site-packages\aiortc\rtp.py", line 89, in get
    values.abs_send_time = unpack("!L", b"\00" + x_value)[0]
struct.error: unpack requires a buffer of 4 bytes

Note sure if it is helpful.

**Comment by chuan-chu** [comment]
This change seems fixed the problem:
rtp.py line 89: check x_value lengh as below:

            elif x_id == self.__ids.abs_send_time:
                try:
                    if len(x_value) == 3:
                        values.abs_send_time = unpack("!L", b"\00" + x_value)[0]
                    elif len(x_value) == 1:
                        values.abs_send_time = unpack("!H", b"\00" + x_value)[0]
                except:
                    pass

**Comment by chuan-chu** [comment]
values.abs_send_time = unpack("!L", bytestring(4 - len(x_value)) + x_value)[0]

**Comment by luz-camacho** [comment]
Same issue as the one I had here: #770 

Through some more research I've found that the culprit is in the newest audio_level feature added to media packets with audio. In the the _next_encoded_frame function in the [rtcrtpsender.py](https://github.com/aiortc/aiortc/blob/main/src/aiortc/rtcrtpsender.py), we computer a new "audio_level" data point which is packed into a new class RTCEncodedFrame.

Having this audio level data point changes up what gets packed in the header extensions. I tracked down the additions to the header extensions and this new audio level feature to this commit: https://github.com/aiortc/aiortc/commit/a9a3cd9cef6ce066dbb07b690652aaff242a3773

If you want another temp fix, you can try forcing the audio_level to None in rtcrtpsender.py, which should stop the new audio level header extension from being added to the packet at all and should make everything parse correctly.

**Comment by chuan-chu** [comment]
Thanks a lot, I did catch that before. Will follow advice if needed. Thanks for your effort!

**Comment by jlaine** [comment]
Duplicate of #770
