### ISSUE TITLE
RoundTripTime in RTC stats

### ISSUE THREAD

**Issue by david-goldb** [aiortc/aiortc#815]
Currently in `aiortc`, the only place we can get the value of `roundTripTime` is at `RTCRemoteInboundRtpStreamStats` after calling `RTCPeerConnection.getStats()` (as described also here at 1.2.28: https://aiortc.readthedocs.io/_/downloads/en/latest/pdf/). 

The question is - Why is this the only place we can access this parameter? 
We have a server, which is the master peer, and it consumes media from multiple viewers. We want it to be independent so we won't have to rely on the viewers to send this `RoundTripTime` to it. The current implementation forces us to send this data to the server because we don't have `RoundTripTime` in the other stats objects, like this one -> `RTCRemoteOutboundRtpStreamStats`.

We saw that there is a way to get this value from this `RTCRemoteOutboundRtpStreamStats`, as written here: https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats. 

Is there a reason it's implemented this way in `aiortc`? 
Can we make it support also `RoundTripTime` in `RTCRemoteOutboundRtpStreamStats`?

Thanks.

**Comment by jlaine** [comment]
> Currently in `aiortc`, the only place we can get the value of `roundTripTime` is at `RTCRemoteInboundRtpStreamStats` after calling `RTCPeerConnection.getStats()` (as described also here at 1.2.28: https://aiortc.readthedocs.io/_/downloads/en/latest/pdf/).

This is *aiortc's* estimate of the RTT, calculated based on the timestamps in the `Receiver Report` blocks we received from the remote party, see:

https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime

> We saw that there is a way to get this value from this `RTCRemoteOutboundRtpStreamStats`, as written here: https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteoutboundrtpstreamstats

That is not the same metric, and it requires first adding support for `Extended Report` blocks, see https://www.rfc-editor.org/rfc/rfc3611

> Is there a reason it's implemented this way in `aiortc`? Can we make it support also `RoundTripTime` in `RTCRemoteOutboundRtpStreamStats`?

The reason is that you haven't yet submitted the PR adding this feature!
